logging:
  level:
    ROOT: 'debug'
    com.vite: 'debug'
    jndi: 'warn'
    org.eclipse.jetty: 'warn'
    org.jose4j: 'warn'
    org.springframework: 'warn'
    org.apache: 'warn'
    o.h.v.internal.xml: 'warn'
    org.jboss.loggin: 'warn'
    o.h.v.internal.engine: 'warn'
    o.h.v.i.e.r: 'warn'

spring:
  main:
    banner-mode: 'off'
